# Generated by Django 4.2 on 2023-05-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chat_rename_text_message_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
