# Generated by Django 4.2 on 2023-05-01 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_message_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message',
        ),
    ]
